apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.gitlab.io/
      chart: gitlab
      targetRevision: 9.11.6
      helm:
        valueFiles:
          - $values/argocd/platform/gitlab/values-local.yaml
    - repoURL: https://github.com/elkouhen/poc-devops-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: gitlab-minio-config-cm
      namespace: gitlab
      jqPathExpressions:
        - '.data["initialize"]'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
